org: tasinmir20
app: test
service: Test

provider:
    name: aws
    runtime: nodejs20.x
    timeout: 30
    environment:
        DB_URI: ${.env:DB_URI}

functions:
    api:
        handler: app.handler
        events:
            - httpApi: "*"

plugins:
    - serverless-dotenv-plugin
    - serverless-offline

custom:
    serverless-offline:
        httpPort: 4000 # Set the desired port here
